services:
  studio:
#    user: "root"
    command: bash -lc "exec su ${BSM_USER} -c 'R --no-save -f Tableros/Explorador_IVs_API_run.R'"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3838/__docs__/"]
      interval: 5s
      timeout: 3s
      retries: 5
